[package]
name = "medist"
version = "0.1.0"
edition = "2021"
author = "mengde"
default-run = "medist"

[[bin]]
name = "medist"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
